spring.application.name=limits-service
server.port=8080

# Connecting Spring Cloud Config Server
spring.config.import=optional:configserver:http://localhost:8888

# Managing Multi-Environment Configurations Base On Profile
spring.profiles.active=qa
spring.cloud.config.profile=qa

# Disable Config Server
# spring.cloud.config.enabled=false

# LIMIT OFFSET Records
limit-offset.minimum = 10
limit-offset.maximum = 1000


