spring.application.name=currency-exchange-microservice
server.port=8000

# Connecting Spring Cloud Config Server
# spring.config.import=optional:configserver:http://localhost:8888
spring.config.import=optional:configserver:

# Disable Spring Cloud Config
spring.cloud.config.enabled=false

# h2database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

# Set Retry request & its duration
resilience4j.retry.instances.sample-api.max-attempts=5
resilience4j.retry.instances.sample-api.wait-duration=3s

# Exponential: Total wait time = 1 + 2 + 4 + 8 = 15 seconds.
# resilience4j.retry.instances.sample-api.enable-exponential-backoff=true
# resilience4j.retry.instances.sample-api.exponential-backoff-multiplier=2

# Zipkin Tracing
management.tracing.sampling.probability=1.0
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
