spring.application.name=spring-cloud-config-server
server.port=8888

# Connecting Spring Cloud Config Repo ( default branch: main)
spring.cloud.config.server.git.uri=file:///home/sher/Desktop/Workspace/Java/git/git-localconfig-repo

# Specific branch
# spring.cloud.config.server.git.default-label=master